spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    openfeign:
      lazy-attributes-resolution: true
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${random.value}}



rabbitmq:
  queue: emisso-cartoes