spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest
  cloud:
    openfeign:
      lazy-attributes-resolution: true
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@${EUREKA_SERVER}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

logging:
  file:
    name: ./logs/log-file.log



rabbitmq:
  queue: emisso-cartoes